# Generated by Django 5.1.1 on 2024-09-26 10:52

import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(unique=True, validators=[products.models.validate_name], verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(validators=[products.models.validate_price], verbose_name='Цена')),
            ],
        ),
    ]
